#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = 0
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    lint_on_the_fly = 1
    lint_on_save = 1
    # enable_ale = 1
    windows_smartclose = "q"
    info_symbol = 'i'
    terminal_cursor_shape = 1
    statusline_separator = "arrow"
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    project_rooter_automatically = 0
    filemanager = "defx"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'checkers'
show_cursor_error = false

[[layers]]
name = 'sudo'

[[layers]]
name = 'vim'

[[layers]]
name = 'git'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 3

[[layers]]
name = 'lang#python'

[[layers]]
  name = "lang#markdown"

[[layers]]
name = 'lang#c'
  clang_executable = "/usr/bin/clang-6.0"
  libclang_path = '/usr/lib/llvm-6.0/lib/libclang.so.1'
  clang_flag = ["-lm"]
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
name= 'debug'

[[layers]]
name = 'fzf'

[[layers]]
name = 'tmux'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'chat'

[[layers]]
name = 'tools'

#=============================================================================
# my own vim plugins
#=============================================================================

[[custom_plugins]]
name = "google/vim-searchindex"
merged = 0

[[custom_plugins]]
name = "junegunn/vim-peekaboo"
merged = 0

[[custom_plugins]]
name = "wellle/tmux-complete.vim"
merged = 0

[[custom_plugins]]
name = "markonm/traces.vim"
merged = 0

[[custom_plugins]]
name = "wellle/targets.vim"
merged = 0

[[custom_plugins]]
name = "vim-scripts/star-search"
merged = 0

[[custom_plugins]]
name = "vim-scripts/YankRing.vim"
merged = 0

[[custom_plugins]]
name = "t9md/vim-quickhl"
merged = 0

[[custom_plugins]]
name = "unblevable/quick-scope"
merged = 0

[[custom_plugins]]
name = "blueyed/vim-diminactive"
merged = 0

[[custom_plugins]]
name = "matze/vim-move"
merged = 0

[[custom_plugins]]
name = "tmhedberg/SimpylFold"
merged = 0

[[custom_plugins]]
name = "yuttie/comfortable-motion.vim"
merged = 0

[[custom_plugins]]
name = "mhinz/vim-signify"
merged = 0

[[custom_plugins]]
name = "vim-scripts/LargeFile"
merged = 0

[[custom_plugins]]
name = "kristijanhusak/defx-icons"
merged = 0

[[custom_plugins]]
name = "jeetsukumaran/vim-pythonsense"
merged = 0

[[custom_plugins]]
name = "junegunn/fzf.vim"
merged = 0

[[custom_plugins]]
name = "jalvesaq/vimcmdline"
merged = 0

[[custom_plugins]]
name = "jacoborus/tender.vim"
merged = 0

[[custom_plugins]]
name = "tpope/vim-obsession"
merged = 0

[[custom_plugins]]
name = "tpope/vim-capslock"
merged = 0

[[custom_plugins]]
name = "vim-scripts/RltvNmbr.vim"
merged = 0
