#!/bin/zsh
# /usr/bin/i3exit

if [[ $EDITOR == '' ]] {
  echo 'no EDITOR is specified, use vim'
  EDITOR=vim
}
echo $EDITOR

# with openrc use loginctl
case $1 in
    zsh)
        $EDITOR /home/$USER/.zshrc
        ;;
    i3)
        $EDITOR /home/$USER/.config/i3/config
        ;;
    i3wm)
        $EDITOR /home/$USER/.config/i3/config
        ;;
    tmux)
        $EDITOR /home/$USER/.tmux.conf.local
        ;;
    conf)
        $EDITOR /home/$USER/scripts/conf
        ;;
    haproxy)
        $EDITOR /home/$USER/.haproxy.cfg
        ;;
    ss)
        $EDITOR /home/$USER/.ss.json
        ;;
    proxychains)
        sudo $EDITOR /etc/proxychains.conf
        ;;
    dunst)
        $EDITOR /home/$USER/.config/dunst/dunstrc
        ;;
    ranger)
        $EDITOR /home/$USER/.config/ranger/rc.conf
        ;;
    termite)
        $EDITOR /home/$USER/.config/termite/config
        ;;
    *)
      {
        $EDITOR /home/$USER/.config/$1/*conf*
      } always {
        echo "== ! conf: missing or invalid argument ! =="
        exit 2
      }
esac

exit 0
